# Default values for dev-starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
nameOverride: ""
fullnameOverride: ""
environment: test

imagePullSecret: githubpackages

app:
  image:
    repository: docker.pkg.github.com/oslokommune/gatekeeper/gatekeeper
    tag: latest
  env:
    - name: BASE_URL
      value: https://gatekeeper.k8s-test.oslo.kommune.no
    - name: CLIENT_ID
      value: gatekeeper
    - name: CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: gatekeeper-client-secret
          key: password.txt
    - name: DISCOVERY_URL
      value: https://login-test.oslo.kommune.no/auth/realms/api-catalog/.well-known/openid-configuration
    - name: ERROR_URL
      value: https://apis.k8s-test.oslo.kommune.no/error
    - name: ORIGIN_WHITELIST
      value: https://apis.k8s-test.oslo.kommune.no;http://localhost:3333
    - name: REDIS_URI
      value: redis://dp-redis:6379
    - name: UPSTREAMS
      value: api-catalog=https://api-catalog.k8s-test.oslo.kommune.no;data=https://api.data-dev.oslo.systems;teams=https://devportal-teams.k8s-test.oslo.kommune.no
  hosts:
    - gatekeeper.api-test.oslo.kommune.no
    - gatekeeper.k8s-test.oslo.kommune.no
