# Default values for dev-starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
nameOverride: ""
fullnameOverride: ""
environment: production

podLabels:
  # loggingEnabled: true if you want your container logs in elastic.
  loggingEnabled: true
  # If prometheusEnabled: true, prometheus server will start scraping this app on url /actuator/prometheus on service.internalPort
  # it will also create a rule for the ingress that tell it to block external access
  prometheusEnabled: false

imagePullSecret: githubpackages

app:
  image:
    repository: docker.pkg.github.com/oslokommune/gatekeeper/gatekeeper
    pullPolicy: Always
  resources:
    limits:
      cpu: 250m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  readinessProbe:
    path: /health
    failureThreshold: 10
    initialDelaySeconds: 10
    timeoutSeconds: 5
  livenessProbe:
    path: /health
    failureThreshold: 10
    initialDelaySeconds: 10
    timeoutSeconds: 5
  volumeMounts: []
    #- name: tmp
    #  mountPath: /app/tmp
  env:
    - name: NODE_ENV
      value: production
    - name: CLIENT_ID
      value: gatekeeper
    - name: CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: gatekeeper-client-secret
          key: password.txt
    - name: REDIS_URI
      value: redis://dp-redis:6379

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 4554

ingress:
  enabled: true
  annotations:
    #Open to Internet
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    #Open to Intranet
    #nginx.ingress.kubernetes.io/whitelist-source-range: 172.28.16.0/24, 10.130.0.0/21, 10.130.40.0/21, 10.130.48.0/21, 10.130.56.0/22, 10.134.183.140/32
    #When sending files in a rest endpoint the request tend to be larger
    #nginx.ingress.kubernetes.io/proxy-body-size: 5m
    #nginx.org/client-max-body-size: 5m
  host:
    subdomain: gatekeeper
  hosts:
    - gatekeeper.api-test.oslo.kommune.no
    - gatekeeper.k8s-test.oslo.kommune.no
  tls: true

nodeSelector: {}
affinity: {}
tolerations: []
