{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dev-starter.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "dev-starter.name" . }}
    helm.sh/chart: {{ include "dev-starter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if or .Values.ingress.annotations (and .Values.podLabels.prometheusEnabled (eq .Values.podLabels.prometheusEnabled true)) }}
  annotations:
    {{- if and .Values.podLabels.prometheusEnabled (eq .Values.podLabels.prometheusEnabled true) }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location /actuator {
        deny all;
        return 403;
      }
    {{- end }}
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
    {{- if and .Values.ingress.tls (eq .Values.ingress.tls true) }}
  tls:
    - hosts:
        - {{ .Values.ingress.host.subdomain }}.k8s{{ template "with-environment" . }}.oslo.kommune.no
  rules:
    - host: {{ .Values.ingress.host.subdomain }}.k8s{{ template "with-environment" . }}.oslo.kommune.no
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.externalPort }}
    {{- end}}
{{- end}}
