apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-starter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dev-starter.name" . }}
    helm.sh/chart: {{ include "dev-starter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if and .Values.podLabels.prometheusEnabled (eq .Values.podLabels.prometheusEnabled true) }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: {{ .Values.service.internalPort }}
    prometheus.io/path: /actuator/prometheus
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort}}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "dev-starter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
